name: CDN Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: .  # Assumes your website files are in the repo root

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
